AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-users-api

  Sample SAM Template for sam-users-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 128
    Runtime: java11
    Architectures:
      - x86_64
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        MY_COGNITO_USER_POOL_ID: AQICAHiiudjxVBWfQJGeANfSFp+9p8hJv6kr7O5YYGWYkNAsuwGSsUqNbc98rceAQ9T6Y/tcAAAAbTBrBgkqhkiG9w0BBwagXjBcAgEAMFcGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMFsrt2kJtw32U2aKEAgEQgCq/wNGEfd/24yb/0VZYhYvCsL6X4DMbvQBqLOCximiuc8MJ618ZB1mTEVI=
        MY_COGNITO_CLIENT_APP_SECRET: AQICAHiiudjxVBWfQJGeANfSFp+9p8hJv6kr7O5YYGWYkNAsuwEFeYNjBFYH93pmd+EP4bZTAAAAcDBuBgkqhkiG9w0BBwagYTBfAgEAMFoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMdS5fjysnMzAIb/XUAgEQgC1xoJaAdc+vqXKqmT5siyMD/T0+v26QZpv//6vF4t1e+XTwxP3EUM1qqnz+UVU=
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/

Resources:
  PostHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: photo-users-api # TEM QUE SER O NOME DA PASTA DO PROJETO
      Handler: br.com.likwi.photoapp.PostHandler::handleRequest
      Events:
        PhotoAppUsers:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: post
  GetHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: photo-users-api # TEM QUE SER O NOME DA PASTA DO PROJETO
      Handler: br.com.likwi.photoapp.GetHandler::handleRequest
      Events:
        PhotoAppUsers:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PhotoAppUsersAPI:
    Description: "API Gateway endpoint create new User"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  PostHandlerFunction:
    Description: "PostHandlerFunction Lambda Function ARN"
    Value: !GetAtt PostHandlerFunction.Arn
  PostHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for PostHandlerFunction function"
    Value: !GetAtt PostHandlerFunctionRole.Arn
